### ISSUE TITLE
Bootstrap Template

### ISSUE THREAD

**Issue by BillChirico** [VolvoxCommunity/Volvox.Helios#22]
Implement a Bootstrap Admin Dashboard template.

**Comment by luther38** [comment]
I have been working on this in a fork.  Going to send all this mock up code to the org in its own branch.

Module Management
- Mimics the discord UI
- Keeps it simple for people who are already use to the layout.
- As we are setting module configuration per servers I figured this would be a good way to display everything.

Module Pages should contain the following information for what I currently targeting
- Description
  - What does this module do for the user
- Example
  - Show the user what to expect with this module
- Configuration
  - Card to let people configure the module for that server
- Post Module Enable
  - If the user needs to do anything in Discord to make sure the module performs as desired.  Example is what should the user do for the Stream Role Module.

Dark Mode is the new default layout.  If anyone desires for a light mode UI let me know and I will work in a method to switch between the two.  

Dashboard
- Looking into placement for this
- Thinking it might get placed as a "Module" in the UI so the data that is displayed is per server.

Home Page
- Now has merged the About Page into the Home Page so the project information is front and center. 
- Currently only gets displayed when a user has not logged in.  This is not final yet but my current thought.
 - New CSS might be made to support none module related information

Privacy Policy
 - New verbage will be generated for this.
 - With the new UI looking into where to place this.
 - Might follow the new Home Page CSS
