### ISSUE TITLE
Voting Module

### ISSUE THREAD

**Issue by BillChirico** [VolvoxCommunity/Volvox.Helios#44]
Module that will allow campaigns to be created and users can vote on the campaign. On starting a campaign the bot will post a message to the specified channel with reactions as the different options.

Campaigns will be added to the database and tracked from the website. Votes will be tallied and tracked in the database based on reactions to the original message.

**Comment by GusTheGray** [comment]
Can probably be a couple of issues:
1. How will the campaigns be added? How will they be tracked?
2. How will users other than the creator of the campaign interact with them? How will votes be tallied and tracked?
