### ISSUE TITLE
Patch Notes Module

### ISSUE THREAD

**Issue by BillChirico** [VolvoxCommunity/Volvox.Helios#54]
Module that will post bot patches notes/change log to a specified channel. Will also be available from the website.

The updates will be tracked in the DB and will then trigger to display to the servers specified channel. The channel will be tracked in the DB and set by the server admin on the module settings. There will be a separate updates page that the user can view current/previous updates.

**Comment by luther38** [comment]
Any reason the patch notes could not be just displayed on the site rather then posting to Discord?  

For the website anyone one who can access the site and manage the configuration of the bot should be valid to view the patch notes.  By the same standpoint no reason why patch notes could not be public.  That way people who are looking around for bots could see that Helios is active.

If the Discord approach is still desired here is my thought.  As an Admin of a server I would like to know about changes but my users wont care as much.  Send patch notes as a PM?  I have seen other bots just post messages to me directly and that way my users don't have to worry about it.

**Comment by BillChirico** [comment]
We need to implement the Headway widget then we can close this issue.

https://headwayapp.co/volvox-changelog
