### ISSUE TITLE
Usage of ReturnUrl parameter in signin (AuthenticationController.cs) results in an unvalidated redirect or forward

### ISSUE THREAD

**Issue by GusTheGray** [VolvoxCommunity/Volvox.Helios#72]
Issue:
Passing a fully qualified domain name (FQDN) to ReturnUrl on /signin will result in a redirect to and arbitrary website.
e.g. www.volvox.tech/signin?ReturnUrl=https://google.com

Proposed solution:
ReturnUrl should be validated as relative path. 
FQDNs should either forced to relative (e.g. www.volvox.tech/signin?ReturnUrl=https://google.com results in a redirect to www.volvox.tech/https://google.com), the domain portion be stripped, or simply throw an error if there is an FQDN submitted.

More info:
https://www.troyhunt.com/owasp-top-10-for-net-developers-part-10/
https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards

**Comment by BillChirico** [comment]
Discord only allows redirect urls to be ones that have already been added to a list of permitted urls

**Comment by GusTheGray** [comment]
I'm aware. I'm not talking about the redirect uri that discord uses.

The code for signing (in authenticationcontroller.cs) also has a parameter called redirecturi that it accepts from the query string on sign-in. This variable is then used to redirect the user after authentication with discord is completed.

**Comment by BillChirico** [comment]
Added to v1
